### ISSUE TITLE
Feature request: Option to disable template prompts, and only use the folder matching templates

### ISSUE THREAD

**Issue by SeriousBug** [numeroflip/obsidian-auto-template-trigger#20]
Hey, love the plugin! I had one feature idea: an option to disable the prompt so only the automatic folder templates are used.

You can already work around to get this behavior by creating an empty template, then assigning it to the root folder. But it would be nice to have a button to just disable it instead. I'm using this plugin to automatically apply a template to my journals, but otherwise I don't use templates for other notes.

**Comment by toldeveloper** [comment]
I thought the exact same thing. Will only be using templates for a specific folder.

**Comment by jose-elias-alvarez** [comment]
> Now there is a disable prompt toggle, in v1.3.0 ( thank you @jose-elias-alvarez for the pr )
> 
> Originally I was unsure about this feature, since even the folder based templates, as a functionality was just an afterthought. As such I was hesitant to even start getting deeper into that direction, yet it looks like there is a need for that.
> 
> The original idea around the plugin was just to simply triggered the template prompt on each note creation. Period. Funny how it evolves, and I'm starting to like this direction as well :D
> 
> Actually I would be very surprised if this note based workflow (I create a note in a specific folder -> a specific template is applied) would not be handled by some other plugins better.

Appreciate the flexibility – to my knowledge, this plugin is the best option for that workflow for those of us using native templates (I believe Templater can do the same thing, but it's far heavier).

**Comment by nizmow** [comment]
Hey, I don't mean to resurrect a closed issue, but 1.3.0 came out a few months ago now and as far as I can see Obsidian is still showing 1.2.2 as the latest version. Any idea why? Is it just a long delay with Obsidian updating their plugins?

<img width="739" alt="Image" src="https://github.com/user-attachments/assets/f9a9251d-b4c3-43bb-bfdf-6e3cfb463b6e" />

**Comment by numeroflip** [comment]
Hey @nizmow  

Thanks for your kind words, and sorry for the late reply. 

I just made a new release a few days ago, and now 1.3.2 should be available there.
